version: '3.8'
services:
  support-system:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=support-system-backend/src/main.py
      - FLASK_RUN_PORT=5002
      - FLASK_ENV=production
    volumes:
      - ./support-system-backend/src/database:/app/support-system-backend/src/database
    restart: unless-stopped
